version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.12
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto para conexiones AMQP
    environment:
      - RABBITMQ_DEFAULT_USER=MateoGonz
      - RABBITMQ_DEFAULT_PASS=astrocomet
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
